
import { User, LotteryPlan } from './types';

export const LOTTERY_PLANS: LotteryPlan[] = [
  // WEEKLY PLANS
  {
    id: 'SILVER_WEEKLY',
    name: 'Silver Weekly',
    tokenPrice: 250,
    totalTokens: 200,
    totalWinners: 10,
    prizePerWinner: 5000,
    prizeName: 'Rs 5,000 Cash',
    drawTime: 'Every Sunday 04:00 PM',
    drawDay: 'Sunday',
    drawCycle: 'WEEKLY',
    colorClass: 'text-slate-500',
    bgClass: 'from-slate-100 to-slate-300',
    icon: '🥈',
    referralThreshold: 10,
    referralRewardCount: 1,
    isReferralEnabled: true,
    isActive: true
  },
  {
    id: 'GOLD_WEEKLY',
    name: 'Gold Weekly',
    tokenPrice: 500,
    totalTokens: 200,
    totalWinners: 10,
    prizePerWinner: 10000,
    prizeName: 'Rs 10,000 Cash',
    drawTime: 'Every Sunday 04:00 PM',
    drawDay: 'Sunday',
    drawCycle: 'WEEKLY',
    colorClass: 'text-amber-500',
    bgClass: 'from-amber-100 to-amber-300',
    icon: '🥇',
    referralThreshold: 10,
    referralRewardCount: 2,
    isReferralEnabled: true,
    isActive: true
  },
  {
    id: 'PLATINUM_WEEKLY',
    name: 'Platinum Weekly',
    tokenPrice: 1000,
    totalTokens: 200,
    totalWinners: 10,
    prizePerWinner: 20000,
    prizeName: 'Rs 20,000 Cash',
    drawTime: 'Every Sunday 04:00 PM',
    drawDay: 'Sunday',
    drawCycle: 'WEEKLY',
    colorClass: 'text-cyan-500',
    bgClass: 'from-cyan-100 to-cyan-300',
    icon: '💎',
    referralThreshold: 10,
    referralRewardCount: 3,
    isReferralEnabled: true,
    isActive: true
  },
  // MONTHLY PLANS
  {
    id: 'CHINA_BIKE_MONTHLY',
    name: 'China Motorcycle',
    tokenPrice: 1500,
    totalTokens: 1000,
    totalWinners: 10,
    prizePerWinner: 65000,
    prizeName: 'China Motorcycle',
    drawTime: 'Every 1st of Month 04:00 PM',
    drawDay: '1st',
    drawCycle: 'MONTHLY',
    colorClass: 'text-red-500',
    bgClass: 'from-red-100 to-red-300',
    icon: '🏍️',
    referralThreshold: 15,
    referralRewardCount: 1,
    isReferralEnabled: true,
    isActive: true
  },
  {
    id: 'CD70_BIKE_MONTHLY',
    name: 'CD 70 Motorcycle',
    tokenPrice: 2000,
    totalTokens: 1000,
    totalWinners: 10,
    prizePerWinner: 110000,
    prizeName: 'CD 70 Motorcycle',
    drawTime: 'Every 1st of Month 04:00 PM',
    drawDay: '1st',
    drawCycle: 'MONTHLY',
    colorClass: 'text-blue-500',
    bgClass: 'from-blue-100 to-blue-300',
    icon: '🛵',
    referralThreshold: 20,
    referralRewardCount: 1,
    isReferralEnabled: true,
    isActive: true
  },
  {
    id: '125_BIKE_MONTHLY',
    name: '125 Motorcycle',
    tokenPrice: 2500,
    totalTokens: 1000,
    totalWinners: 10,
    prizePerWinner: 180000,
    prizeName: '125 Motorcycle',
    drawTime: 'Every 1st of Month 04:00 PM',
    drawDay: '1st',
    drawCycle: 'MONTHLY',
    colorClass: 'text-slate-900',
    bgClass: 'from-slate-700 to-slate-900',
    icon: '🏍️💨',
    referralThreshold: 25,
    referralRewardCount: 1,
    isReferralEnabled: true,
    isActive: true
  },
  {
    id: 'UMRAH_MONTHLY',
    name: 'Umrah Ticket',
    tokenPrice: 3000,
    totalTokens: 1000,
    totalWinners: 10,
    prizePerWinner: 250000,
    prizeName: 'Umrah Ticket',
    drawTime: 'Every 1st of Month 04:00 PM',
    drawDay: '1st',
    drawCycle: 'MONTHLY',
    colorClass: 'text-emerald-600',
    bgClass: 'from-emerald-100 to-emerald-300',
    icon: '🕋',
    referralThreshold: 30,
    referralRewardCount: 1,
    isReferralEnabled: true,
    isActive: true
  }
];

export const MOCK_USER: User = {
  id: '1',
  firstName: 'Dilbar',
  lastName: 'Ali',
  username: 'premium_member',
  email: 'user@example.com',
  mobile: '03177730425',
  role: 'USER', 
  walletBalance: 2500,
  referralCode: 'LUCKY2024',
  referralsCount: 15,
  activeReferrals: 8,
  totalWinnings: 15000,
  planReferralStats: {
    'SILVER_WEEKLY': 8,
    'GOLD_WEEKLY': 4,
    'PLATINUM_WEEKLY': 2
  }
};
